# Generated by Django 2.2.4 on 2019-09-16 05:54

from django.db import migrations, models
import picture.storage


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturepost',
            name='image',
            field=models.ImageField(storage=picture.storage.CosStorage(), upload_to='', verbose_name='图片'),
        ),
    ]
