# Generated by Django 2.2.4 on 2019-09-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_auto_20190916_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturepost',
            name='image2',
            field=models.ImageField(default=0, upload_to='imgs', verbose_name='本地图片'),
            preserve_default=False,
        ),
    ]
