# Generated by Django 2.2.4 on 2019-09-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_picturepost_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picturepost',
            name='image2',
        ),
    ]
