# Generated by Django 2.2.4 on 2019-09-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190905_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='upadted',
            new_name='updated',
        ),
    ]
