# Generated by Django 2.2.4 on 2019-09-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190906_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
